### PR TITLE
Don't initialize `SERVER_PORT` in ENV to empty String

### LINKED ISSUE #107: `Rack::Lint::LintError: env[SERVER_PORT] is not an Integer` when using `rackup` with `--env development`
### System Information

 - **OS**:            `Linux bb13cf4bee22 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 GNU/Linux`
 - **Ruby**:         `ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [aarch64-linux]`
 - **Version**:     `0.7.44`

### Description

When using `rackup` to start Iodine, providing the `--env development` option (which sets up default Rack middleware), all requests raise `Rack::Lint::LintError` with an error concerning the `SERVER_PORT` value. I've confirmed that it is an empty String (`""`) in the `env` Hash object.

This seems to be dependent on the `Host` header sent by the client/loadbalancer. Some will include the port, which in case everything is fine, but if the port is excluded, Iodine sets the env variable to an empty string, which fails `Rack::Lint`. It should leave it `nil` or set it to a default for the scheme.

### Rack App to Reproduce

```ruby
APP = {|env| [200, {}, ["Hello World"]] }
run APP
```

### Testing code

```sh
# Run rackup in background
rackup example.ru --env development --server iodine &

# Send curl with host header excluding port (will be broken)
curl http://localhost:9292 -H "Host: example.com"

# Send curl with Host header including port (will work)
curl http://localhost:9292 -H "Host: example.com:9292"
```

### Expected behavior

```
curl http://localhost:9292 -H "Host: example.com"
Hello World
```

### Actual behavior

```
curl http://localhost:9292 -H "Host: example.com"
Rack::Lint::LintError: env[SERVER_PORT] is not an Integer
```

### PR DESCRIPTION
**Pull request by adam12**
The Rack specification states that if `SERVER_PORT` is present,
it must be a numeric value.

When initializing the Hash, the `SERVER_PORT` key is set, but
never filled in.

Closes #107 

I'm not sure if this is the most optimal solution but I wanted to offer something.

### CODE REVIEW

File: ext/iodine/iodine_http.c [hunk 1]
```diff
@@ -365,7 +365,11 @@ static inline VALUE copy2env(iodine_http_request_handle_s *handle) {
   if (*pos == 0) {
     rb_hash_aset(env, SERVER_NAME,
                  rb_enc_str_new(tmp.data, tmp.len, IodineBinaryEncoding));
-    rb_hash_aset(env, SERVER_PORT, QUERY_ESTRING);
+    if (RSTRING_LEN(QUERY_ESTRING) != 0) {
```
Comment (boazsegev) [inline ext/iodine/iodine_http.c:368]: This is my fault for having poorly named variables, but... the `ESTRING` in `QUERY_ESTRING` stands for an **Empty** String, its length is always zero and it's used almost everywhere I needed an empty frozen string (to avoid creating multiple objects)... so there's really no need for this `if` statement.

File: ext/iodine/iodine_http.c [hunk 2]
```diff
@@ -365,7 +365,11 @@ static inline VALUE copy2env(iodine_http_request_handle_s *handle) {
...
+      rb_hash_aset(env, SERVER_PORT, QUERY_ESTRING);
+    } else {
+      rb_hash_delete(env, SERVER_PORT);
```
Comment (boazsegev) [inline ext/iodine/iodine_http.c:371]: I think that using `rb_hash_aset(env, SERVER_PORT, Qnil)` would be both faster here and in the client code.

Using the `delete` operator can cause possible hash map misses when searching for a value and these misses are slower than finding a `nil` value.

This should work with the way the Linter middleware checks the value: https://github.com/rack/rack/blob/d15dd728440710cfc35ed155d66a98dc2c07ae42/lib/rack/lint.rb#L284

**Review by boazsegev — CHANGES_REQUESTED** [review]
Thank you for discovering this issue and providing a possible fix.

I love the general approach and its simplicity, but I think the change would have been more effective by replacing `QUERY_ESTRING` with `Qnil` in the `rb_hash_aset` function call you replaced:

```c
rb_hash_aset(env, SERVER_PORT, Qnil);
```

You can read my notes as to why.

If you update the PR that would be great, if not, I'll do it myself... eventually. I have a family crisis so I'm not really working much these days.

Thanks!

File: ext/iodine/iodine_http.c (hunk 2 above)
Comment (adam12) [reply ext/iodine/iodine_http.c:371]: Unfortunately I tried `Qnil` originally, and it failed. I just tried it again to confirm.

`ERROR: Iodine caught an unprotected exception - Rack::Lint::LintError: env variable SERVER_PORT has non-string value nil`

```diff
diff --git a/ext/iodine/iodine_http.c b/ext/iodine/iodine_http.c
index 4f7475f..a9ca702 100644
--- a/ext/iodine/iodine_http.c
+++ b/ext/iodine/iodine_http.c
@@ -365,11 +365,7 @@ static inline VALUE copy2env(iodine_http_request_handle_s *handle) {
   if (*pos == 0) {
     rb_hash_aset(env, SERVER_NAME,
                  rb_enc_str_new(tmp.data, tmp.len, IodineBinaryEncoding));
-    if (RSTRING_LEN(QUERY_ESTRING) != 0) {
-      rb_hash_aset(env, SERVER_PORT, QUERY_ESTRING);
-    } else {
-      rb_hash_delete(env, SERVER_PORT);
-    }
+    rb_hash_aset(env, SERVER_PORT, Qnil);
   } else {
     rb_hash_aset(
         env, SERVER_NAME,
```

This is because the described spec is wrong, and non-String values are failures too, if they don't contain a period: https://github.com/rack/rack/blob/d15dd728440710cfc35ed155d66a98dc2c07ae42/lib/rack/lint.rb#L308-L315

**Comment by adam12** [comment]
> I have a family crisis so I'm not really working much these days.

I'm sorry to hear that. I hope things improve for you.

File: ext/iodine/iodine_http.c (hunk 2 above)
Comment (adam12) [reply ext/iodine/iodine_http.c:371]: Actually, I think the spec is right, they are just using the presence of `nil` to guard on the coercion through `Integer`. So it looks like it allows `nil`, but in essence they only care in that scenario that they don't coerce a `nil` value and trigger an error at that line.

My guess anyways.

Comment (adam12) [reply ext/iodine/iodine_http.c:371]: I could drop the conditional and always delete. Or could we remove the empty string that is initialized earlier in this file (`rb_hash_aset(env_template_no_upgrade, SERVER_PORT, QUERY_ESTRING);`)?

```
diff --git a/ext/iodine/iodine_http.c b/ext/iodine/iodine_http.c
index 4f7475f..7f47c17 100644
--- a/ext/iodine/iodine_http.c
+++ b/ext/iodine/iodine_http.c
@@ -365,11 +365,7 @@ static inline VALUE copy2env(iodine_http_request_handle_s *handle) {
   if (*pos == 0) {
     rb_hash_aset(env, SERVER_NAME,
                  rb_enc_str_new(tmp.data, tmp.len, IodineBinaryEncoding));
-    if (RSTRING_LEN(QUERY_ESTRING) != 0) {
-      rb_hash_aset(env, SERVER_PORT, QUERY_ESTRING);
-    } else {
-      rb_hash_delete(env, SERVER_PORT);
-    }
+    rb_hash_delete(env, SERVER_PORT);
   } else {
     rb_hash_aset(
         env, SERVER_NAME,
```

**Comment by adam12** [comment]
I updated the patch to skip initializing the Hash with the `SERVER_PORT` key and an empty string as it's value. I also deleted the line that sets the empty string if the Host header contains no port reference.

**Comment by boazsegev** [comment]
Thanks for the updates!

I hope to look into this in the next few days, however, I am slightly worried that a ` rb_hash_aset(env, SERVER_PORT,...)` could cause a re-hashing of the keys and memory allocations in the hash map. 

Since this will likely be performed for every request and within the GIL, it could create a performance penalty for setups that cause clients to use `host:port` (is this common?).

This was the reason for creating the `env` template and pre-initializing the common keys - avoiding the re-hashing algorithm as keys are added.

On the other hand, `rb_hash_delete(env, SERVER_PORT)` shouldn't cause a rehashing, but it would invoke a smaller performance penalty for the regular `host` headers that have no `:port` information (which might be better for most use cases).

Anyway, I'll have a look at the code later and think it over.

Cheers!

**Comment by boazsegev** [comment]
I was sure I already accepted this... instead it was just waiting in the backlog, quietly snoozing between the cracks...

Thanks again for the PR!

**Comment by adam12** [comment]
:joy: I didn't want to pester. Life of the OSS developer and all that.

Hope all is well with you. Cheers!

**Comment by yildizsc** [comment]
Thank you very much @boazsegev @adam12
